### ISSUE TITLE
RuntimeError in 'ifc-to-json' example

### ISSUE THREAD

**Issue by ngorlani** [IFCjs/hello-world#2]
Hi,
when I start the node project 'ifc-to-json' I receive this error:
![image](https://user-images.githubusercontent.com/91492685/137586738-3068f151-40a3-4037-aea0-a31e608551ec.png)

In the same way, if I serve the frontend project, when I try to create a json from the ifc file I can see the same error in console:
![image](https://user-images.githubusercontent.com/91492685/137586767-8d99f392-3103-46e6-81b3-48ddf784ad41.png)

thanks

**Comment by agviegas** [comment]
Hi! As I said, this is happening because the WASM file that you are using doesn't have the same version as the library version. I tried this project and works on my end. There's some console errors for the Node example I'm aware of; I'll take a look. But your problem won't solve until you make sure you are using the same version for the WASM and for the library.

**Comment by agviegas** [comment]
![image](https://user-images.githubusercontent.com/56475338/140628917-16c66138-128f-4b4f-aacd-f26635cba504.png)
The frontend example works for me for [this model.](https://drive.google.com/file/d/1HaZiDH7_HaUlEoCTsjj9RuhtnLQynLbj/view?usp=sharing) Notice that it's a small model; as I said before, this is not a code you should put in your application, it's just a simple demonstration of how to use the API. 

The node example throws some warnings in the console, but is also able to generate the JSON file of an IFC. 

This might not work with bigger models, and we won't solve it because it probably would make things a bit more complex, so it wouldn't be a "hello world" example anymore. If you are encountering errors in your production app, I'd suggest you to post those specific errors in the correspondent repository.

Thanks! 🙂
